### ISSUE TITLE
[Must]すでにsignupしたユーザーのvalidationがされていないため、2重3重に登録が可能になってしまう。

### ISSUE THREAD

**Issue by shunMB** [taruyar/numa-token-api-signup#1]
タイトルの通りです。
現状では登録後に再度登録を行うと、DynamoDBでaddress/public key/private keyが書き換えられるようになっています。
BFFを通じて来るlineクライアント側からの初回登録のみを受け入れるように、既に登録済みのユーザーは登録できないようにし、それに応じたステータスコードとメッセージを返す必要があります。
*この話すでにしていたらごめんなさい、、、それ以外はいいコードだと思います！

**Comment by taruyar** [comment]
isRegistered関数を設け、解決したよ

**Comment by taruyar** [comment]
ありがとうございます
